---
author: "Gabriela Palomo"
output: html_document
bibliography: scrGlossary.bib
nocite: | 
  @royle_spatial_2013, @sutherland_NA, @rovero2016camera
...


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Glossary of the most common used terms in Spatial Capture Recapture (SCR) models 

##### I include [*] for the context in which the term is most used. If a term has a synonym I include it at the end of the definition using _Syn._ 

1. **Abundance [Ecology]:** total number of individuals in an area at a given time. 

1. **Abundance [SCR]:** total number of activity centers in an area at a given time.

1. **Activity center:** is the centroid of the space that an individual occupies or uses during the period in which traps are active. Syn. Home range center.

1. **Camera trap array:** a set of camera traps organized in a predetermined spatial pattern and location in a study area. A study may include multiple arrays sampled sequentially in a study season. 

1. **Connectivity:** The degree to which the landscape facilitates or impedes movement among locations. 

1. **Data augmentation (DA):** it is a reparametrization of the "complete data" model. Basically, the DA is embedded into a larger data set ending with M _rows_ > N _rows_ (rows = individuals). The model is re-expressed conditional on M instead of N (which can be unknown). Through a Bernoulli sampling process we can determine if an individual of M is also a member of N. Used in SCR models with unknown population size (N) under a Bayesian framework. 

1. **Density [in ecology]:** number of individuals per area at a given time. 
1. **Density [in SCR]:** number of activity centers per area at a given time. 

1. **Detection probability:** used mostly in SCR context. Animals can encounter a trap, but most study designs cannnot disentagle visitation from detection. It usually depends on the context the research is being taking place because you cannot say capture probability if you are using camera traps, hair snares, or scats because you are technically not capturing individuals. Syn. encounter probability, capture probability. 

1. **Ecological distance:** the least cost path between two points estimated from encounter history data. 

1. **Encounter probability:** used mostly in occupancy context. Syn. detection probability. 

1. **Euclidean distance:** the straight-line distance between two points. 

1. *habitat mask:* this mask is used in SCR models to define the outer limit of the state space because animals could occupy the area beyond the mask but the probability of detecting them outside the mask should be small. It also encircles the sites near the detector array that have the potential to be occupied (habitat) from the non-occupied sites. 

1. **Home range:** defined in SCR as the area used by an organism during some time period.

1. **Homogeneous point process (HPP):** a spatial point process that has a constant intensity parameter. In SCR the constant intensity parameter is expected density. 

1. **Individual encounters:** capture or encounter of one individual using a trap or detector. One of the assumptions of SCR models. To build an SCR model individual encounters within and among traps must be independent. 

1. **Inhomogeneous point process (IPP):** a spatial point process for which the intensity parameter is location specific (spatially varying). The intensity parameter is density. 

1. **Latent variable:** a variable not directly observed, but inferred from data. E.g., activity center. 

1. **Occasion (k):** a unique and independent temporal interval composed of repeated detection of individuals across sites. It could be one night or several nights pooled together. Marices are built by parting the overall survey effort in occasions (temporal intervals) which are usually the columns. Syn. sampling occasion. 

1. **Occupancy:** the proportion of sites occupied by a target species. Occupy means that at least one individual is present at the site. 

1. **Session:** a stratum defining meaningful grouping for purposes of data collection. Usually a session is defined by a site, a year, or a combination of both. 

1. **Spatial capture recapture (SCR):** a hierarchical capture-recapture (CR) model. An extension  of CR to make use of encounter location data to study spatial aspects of animal populations. These models can be used for spatial models of density, resource selection, transience/dispersal. SCR models describe the probability of encounter in a trap, conditional on where an individual (i) lives (Si). The biological process in SCR models is how individual sare distributed in space. Ecologists can use SCR models to address questions regarding: 1) spatial patterns in density, 2) resource selection or space usage, 3) dispersal, transience, and 4) landscape/connectivity. SCR models are basically a unified framework to draw inferences about density and spatial population processes. 

1. **Spatial encounter history [SCR] (y<sub>ijk</sub>):** the spatially explicity observation data matrix representing which individual (i) was encountered when (k) and where (j). Yijk = individual i was detected (y=1) or not (y=0) at trap j in sampling occasion k. The observation model can either be a count or a binary detection model. although, in this definition it is implied that it is a 3D array, it should be noted that one can sum captures across occasions if there are no time effects. 

1. **State space (S):** an area containing all plausible activity centers of individuals observed during a study. It could be a discrete or continuous area containing all plausible activity centers of the detected individuals. Syn. Area of integration. 

1. **State variable:** the parameter or parameters of a population being studied. E.g., a state variable could be abundance, or a proxy of it, occupancy. 

1. **survey effort:** total number of days (or nights) independent traps (vs. paired traps) worked during a survey. Syn. sampling effort. 

1. **Trap:** the spatial unit at which individuals are observed. The location of an observation si the centroid of the pixel within which the observation was made. Syn. locator. 

### Symbols

1. *d<sub>j</sub>:* distance between a trap and activity center. The activity centers are usually unobserved, therefore dj is usually a latent variable. 

1. *s<sub>i</sub>*: two dimensional spatial coordinate of the activity center for individual i. 

1. *k:* occasions. 

1. *i:* individuals.

1. *j:* traps or detectors. 

1. *S:* state space. 

1. *p<sub>ij</sub>:* encounter probability which depends on both individual and trap. 

1. *s<sub>i</sub>:* a two-dimensional spatial coordinate which is the activity center of individual i. 

### References 

